/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    Enterprise: typeof import('./src/components/icons/enterprise.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/icons/Icon.vue')['default']
    IconCard: typeof import('./src/components/icons/IconCard.vue')['default']
    IconDayMode: typeof import('./src/components/icons/IconDayMode.vue')['default']
    IconEnterprise: typeof import('./src/components/icons/IconEnterprise.vue')['default']
    IconHotel: typeof import('./src/components/icons/IconHotel.vue')['default']
    IconLightening: typeof import('./src/components/icons/IconLightening.vue')['default']
    IconLightning: typeof import('./src/components/icons/IconLightning.vue')['default']
    IconNightMode: typeof import('./src/components/icons/IconNightMode.vue')['default']
    IconPlane: typeof import('./src/components/icons/IconPlane.vue')['default']
    IconTrain: typeof import('./src/components/icons/IconTrain.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconWaterDrop: typeof import('./src/components/icons/IconWaterDrop.vue')['default']
    InconLogo: typeof import('./src/components/icons/InconLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortItem: typeof import('./src/components/ShortItem.vue')['default']
    UserMainButton: typeof import('./src/components/UserMainButton.vue')['default']
    UserMainCarousekl: typeof import('./src/components/UserMainCarousekl.vue')['default']
    UserMainInfor: typeof import('./src/components/UserMainInfor.vue')['default']
    UserMainLeft: typeof import('./src/components/UserMainLeft.vue')['default']
    UserMainRight: typeof import('./src/components/UserMainRight.vue')['default']
  }
}
